name = "DistributedFactorGraphs"
uuid = "b5cc3c7e-6572-11e9-2517-99fb8daf2f04"
version = "0.5.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON2 = "2535ab7d-5cd8-5a07-80ac-9b1792aadce3"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Neo4j = "d2adbeaf-5838-5367-8a2f-e46d570981db"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Colors = "0.8, 0.9, 0.10, 0.11"
Distributions = "0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 0.25, 1"
DocStringExtensions = "0.7, 0.8, 0.9, 0.10, 1"
GraphPlot = "0.3.1, 0.4"
Graphs = "0.10.2, 0.11, 1"
JSON2 = "0.3.1"
LightGraphs = "1.2, 1.3"
MetaGraphs = "^0.6.3"
Neo4j = "2"
Reexport = "0.2, 0.3, 0.4, 0.5, 1"
Requires = "0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 1"
julia = "0.7, 1"

[extras]
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GraphPlot", "Pkg"]
